swagger: '2.0'
info:
  description: 'Rawbot'
  version: '1.0.0'
  title: 'RawBot'
  termsOfService: ''
  contact:
    email: 'gart.algar@gmail.com'
basePath: '/rawbot/v1'
tags:
  - name: 'channel'
    description: 'info about channel'
schemes:
  - 'https'
  - 'http'
paths:
  /channel:
    put:
      tags:
        - 'channel'
      summary: 'Add a channel for the rawbot to sits'
      description: 'Returns a map of channels'
      operationId: 'addChannel'
      responses:
        200:
          description: 'successful operation'
          schema:
            type: 'object'
            items:
              $ref: '#/definitions/channel'
    get:
      tags:
        - 'channel'
      summary: 'Returns channel where rawbot sits'
      description: 'Returns a map of channels'
      operationId: 'getConnectedChannel'
      produces:
        - 'application/json'
      parameters: []
      responses:
        200:
          description: 'successful operation'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/channel'
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: 'apiKey'
    name: 'api_key'
    in: 'header'
definitions:
  Channel:
    type: 'object'
    properties:
      name:
        type: 'string'
